package com.church.YPortal.mapper;

import com.church.YPortal.dto.address.AddressResponse;
import com.church.YPortal.dto.address.CreateAddressRequest;
import com.church.YPortal.entity.Address;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

@Mapper(componentModel = "spring")
public interface AddressMapper {

    /**
     * Converts CreateAddressRequest DTO into an Address entity.
     *
     * IMPORTANT:
     * - id is ignored because it is generated by the database
     * - member is ignored because the parent Member entity
     *   is assigned in the service layer
     */
    @Mapping(target = "id", ignore = true)
    Address toEntity(CreateAddressRequest request);

    /**
     * Converts an Address entity into an AddressResponse DTO.
     *
     * Used when returning member address information.
     */
    AddressResponse toResponse(Address address);
}
