package com.church.YPortal.mapper;

import com.church.YPortal.dto.education.CreateEducationRequest;
import com.church.YPortal.dto.education.EducationResponse;
import com.church.YPortal.dto.member.MemberResponse;
import com.church.YPortal.entity.Education;
import com.church.YPortal.entity.Member;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

import java.util.List;

@Mapper(componentModel = "spring")
public interface EducationMapper {

    /**
     * Converts CreateEducationRequest DTO into an Education entity.
     *
     * IMPORTANT:
     * - id is ignored because it is generated by the database
     * - member is ignored because it will be set manually
     *   in the service layer after the Member is created
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "member", ignore = true)
    Education toEntity(CreateEducationRequest request);

    /**
     * Converts an Education entity into an EducationResponse DTO.
     *
     * Used when returning member education details to the client.
     */
    EducationResponse toResponse(Education education);

    /**
     * Converts a list of Education entities into
     * a list of MemberResponse DTOs.
     */
    List<EducationResponse> toResponseList(List<Education> educations);

}

