package com.church.YPortal.mapper;

import com.church.YPortal.dto.employment.CreateEmploymentRequest;
import com.church.YPortal.dto.employment.EmploymentResponse;
import com.church.YPortal.entity.Employment;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

@Mapper(componentModel = "spring")
public interface EmploymentMapper {

    /**
     * Converts CreateEmploymentRequest DTO into an Employment entity.
     *
     * IMPORTANT:
     * - id is ignored because it is generated by the database
     * - member is ignored because the relationship is handled
     *   in the service layer
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "member", ignore = true)
    Employment toEntity(CreateEmploymentRequest request);

    /**
     * Converts an Employment entity into an EmploymentResponse DTO.
     *
     * Used when returning employment history in API responses.
     */
    EmploymentResponse toResponse(Employment employment);
}
