package com.church.YPortal.mapper;

import com.church.YPortal.dto.member.CreateMemberRequest;
import com.church.YPortal.dto.member.MemberResponse;
import com.church.YPortal.dto.member.UpdateMemberRequest;
import com.church.YPortal.entity.Member;
import org.mapstruct.*;

import java.util.List;

/**
 * MemberMapper
 *
 * This mapper handles conversion between:
 *  - Member entity (database model)
 *  - Member request DTOs (Create / Update)
 *  - Member response DTO
 *
 * MapStruct generates the implementation automatically at build time.
 */
@Mapper(
        componentModel = "spring", // Registers mapper as a Spring Bean
        uses = {
                // These mappers are used for nested objects
                EducationMapper.class,
                EmploymentMapper.class,
                AddressMapper.class
        }
)
public interface MemberMapper {

    /**
     * Converts CreateMemberRequest DTO into a Member entity.
     *
     * IMPORTANT DESIGN DECISIONS:
     * - id is ignored because it is generated by the database
     * - educations, employments, and addresses are ignored here
     *   because they are saved separately (usually in the service layer)
     */
    @Mapping(target = "id", ignore = true)
    Member toEntity(CreateMemberRequest request);


    /**
     * Converts a Member entity into a MemberResponse DTO.
     *
     * Because we declared `uses = {...}`,
     * MapStruct will automatically:
     * - map educations using EducationMapper
     * - map employments using EmploymentMapper
     * - map addresses using AddressMapper
     */
    MemberResponse toResponse(Member member);

    /**
     * Converts a list of Member entities into
     * a list of MemberResponse DTOs.
     */
    List<MemberResponse> toResponseList(List<Member> members);

    /**
     * Updates an existing Member entity using UpdateMemberRequest.
     *
     * KEY BEHAVIOR:
     * - Null values from the request are ignored
     * - Only provided fields are updated
     * - Nested collections are ignored and handled separately
     *
     * @MappingTarget tells MapStruct to update
     * the existing entity instead of creating a new one.
     */
    @BeanMapping(
            nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE
    )
    void updateEntity(
            UpdateMemberRequest request,
            @MappingTarget Member member
    );
}
