package com.church.YPortal.mapper;


import com.church.YPortal.dto.education.EducationResponse;
import com.church.YPortal.dto.youthExecutives.CreateExecutiveRequest;
import com.church.YPortal.dto.youthExecutives.ExecutiveResponse;
import com.church.YPortal.entity.Education;
import com.church.YPortal.entity.YouthExecutive;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;


@Mapper(componentModel = "spring")
public interface YouthExecutiveMapper {



    /**
     * Converts CreateExecutiveRequest DTO into a YouthExecutive entity.
     *
     * IMPORTANT:
     * - id is ignored because it is generated by the database
     * - member is ignored because it will be set manually
     *   in the service layer after the Member is created
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "member", ignore = true)
    YouthExecutive toEntity(CreateExecutiveRequest request);


    /**
     * Converts a YouthExecutive entity into an ExecutiveResponse DTO.
     *
     * Used when returning youth executive details to the client.
     */
    ExecutiveResponse toResponse(YouthExecutive youthExecutive);

}
